server:
  port: 9095  
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  
spring:
  cloud:
    gateway:
      routes:
      - id: after_route
        uri: http://10.1.0.131:8199/
        predicates:
        - Path=/baeldung/
management:
  endpoints:
    web:
      exposure:
        include: "*'
