server:
  port: 8088
eureka:
  instance:
   preferIpAddress: true
   hostname: 10.1.0.131
   metadataMap: 
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registry-fetch-interval-seconds: 5
    registerWithEureka: true
    fetchRegistry: true
    healthcheck.enabled: true
    serviceUrl:
      defaultZone: http://10.1.0.131:9096/eureka
    eureka-server-connect-timeout-seconds: 10
    eureka-server-read-timeout-seconds: 10
      
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          predicates:
          - name: Path
            args:
              pattern: "'/'+serviceId+'/**'"
#          filters: 
#          - name: AddRequestHeader
#            args: 
#             name: "'foo'"
#             value: "'bar'"
#          - name: RewritePath
#            args:
#              regexp: "'/' + serviceId + '/(?<remaining>.*)'"
#              replacement: "'/${remaining}'"

management:
  endpoints:
    web:
      exposure:
        include: '*'
